### ISSUE TITLE
Optional<String> not working with @javax.validation.constraints.Pattern

### ISSUE THREAD

**Issue by Sotec-IoT** [kokuwaio/micronaut-openapi-codegen#49]
When using a parameter which schema has a pattern inside like:

```   
post:
   parameters:     
        - in: query
          name: version
          required: false
          schema:
            type: string
            minLength: 1
            pattern: '^\d+\.\d+\.\d+$'
```

the tool resolves it to:

```@javax.validation.constraints.Pattern(regexp = "^\\d+\\.\\d+\\.\\d+$")
			@javax.validation.constraints.Size(min = 1)
			@javax.annotation.Nonnull
			@io.micronaut.http.annotation.QueryValue(value = "version")
			java.util.Optional<java.lang.String> version
```

which itself leads to the following exception when called:
 HV000030: No validator could be found for constraint 'javax.validation.constraints.Pattern' validating type 'java.util.Optional<java.lang.String>'. Check configuration for 'findServices.versionOptional
 
even when the tool behaves as expected, the combination of Optional and Pattern don't seem to work
