### ISSUE TITLE
Mapping of array of unique items to Java set is incomplete

### ISSUE THREAD

**Issue by kiwi-oss** [kokuwaio/micronaut-openapi-codegen#51]
The schema definition of an array with unique strings correctly generates a Java set of strings:

```yaml
MapWithArraysOfUniqueStrings:
  type: object
  additionalProperties:
    type: array
    items:
      type: string
    uniqueItems: true
```
```java
private java.util.Map<String, Set<java.lang.String>> mapField;
```
However, `Set` is neither fully qualified nor is it imported. This leads to compile errors like this one:

```
SomeClass.java:42: error: cannot find symbol
        private java.util.Map<String, Set<java.lang.String>> mapField;
                                      ^
  symbol:   class Set
  location: class SomeClass
```

I have tried to add the following import mapping in `build.gradle`:

```gradle
openApiGenerate {
	generatorName = "micronaut"
	// ...
	importMappings = [Set: "java.util.Set"]
}
```
~~Unfortunately, then I get another error:~~

> ~~Cannot set the value of a property of type java.util.Map using an instance of type java.util.ArrayList.~~

Edit: I corrected an error in the Gradle syntax. Fixing it resulted again in the errors about the missing symbol.

I assume all of this happens because the mapping of unique-item arrays is not complete:
1. It has to be mapped to `java.util.Set`
2. ~~`HashSet` has to be instantiated instead of `ArrayList`~~
