### ISSUE TITLE
Generation of `Optional` for parameters can't be disabled

### ISSUE THREAD

**Issue by kiwi-oss** [kokuwaio/micronaut-openapi-codegen#52]
I have a query parameter that is not required:

```yaml
parameters:
  - name: someparam
    in: query
    required: false
    content:
      application/json:
        schema:
          type: object
          additionalProperties: true
```
This is generated in the client interface as:

```java
@javax.annotation.Nonnull
@io.micronaut.http.annotation.QueryValue(value = "someparam")
java.util.Optional<java.util.Map<String, Object>> someparam
```
The `Optional` is then wrongly serialised, e.g. passing `Optional.empty()` results in calling `/path?someparam=Optional.empty` instead of the expected `/path`.

I have turned off usage of `Optional` for parameters as described in the readme file:

```gradle
openApiGenerate {
	generatorName = "micronaut"
	// ...
	configOptions = [
		useOptionals: "false"
	]
}
```
Unfortunately, this has no effect – the parameter is generated the same.

This might be related to #49.
